"""add_emotional_fields_to_menu_item

Revision ID: 6579641ea68a
Revises: 20260930_0004
Create Date: 2026-10-02 12:32:36.387068
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '6579641ea68a'
down_revision: str | None = '20260930_0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('customers', 'language',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('UK', 'RU', 'EN', name='language', native_enum=False, length=20),
               existing_nullable=False)
    op.alter_column('customers', 'country',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'city',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('customers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('customers_phone_key'), 'customers', type_='unique')
    op.drop_constraint(op.f('customers_telegram_user_id_key'), 'customers', type_='unique')
    op.drop_index(op.f('ix_customers_telegram_user_id'), table_name='customers')
    op.create_index(op.f('ix_customers_telegram_user_id'), 'customers', ['telegram_user_id'], unique=True)
    op.drop_constraint(op.f('uq_generated_file_kind'), 'generated_files', type_='unique')
    op.alter_column('image_cache', 'model',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('image_cache_cache_key_key'), 'image_cache', type_='unique')
    op.drop_index(op.f('ix_image_cache_cache_key'), table_name='image_cache')
    op.create_index(op.f('ix_image_cache_cache_key'), 'image_cache', ['cache_key'], unique=True)
    op.add_column('menu_items', sa.Column('menu_description', sa.Text(), nullable=True))
    op.add_column('menu_items', sa.Column('drink_pairing', sa.Text(), nullable=True))
    op.add_column('menu_items', sa.Column('romantic_price', sa.String(length=255), nullable=True))
    op.add_column('menu_items', sa.Column('ingredients', sa.JSON(), nullable=True))
    op.add_column('menu_items', sa.Column('recipe', sa.Text(), nullable=True))
    op.add_column('menu_items', sa.Column('prep_minutes', sa.Integer(), nullable=True))
    op.add_column('menu_items', sa.Column('cook_minutes', sa.Integer(), nullable=True))
    op.alter_column('menu_items', 'title',
               existing_type=sa.VARCHAR(length=180),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('ix_menu_items_status'), table_name='menu_items')
    op.drop_constraint(op.f('uq_menu_item_position'), 'menu_items', type_='unique')
    op.drop_column('menus', 'title')
    op.drop_column('menus', 'language')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menus', sa.Column('language', postgresql.ENUM('UK', 'RU', 'EN', name='menu_language_enum'), server_default=sa.text("'UK'::menu_language_enum"), autoincrement=False, nullable=True))
    op.add_column('menus', sa.Column('title', sa.VARCHAR(length=180), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_menu_item_position'), 'menu_items', ['menu_id', 'category', 'position'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_menu_items_status'), 'menu_items', ['generation_status'], unique=False)
    op.alter_column('menu_items', 'title',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=180),
               existing_nullable=False)
    op.drop_column('menu_items', 'cook_minutes')
    op.drop_column('menu_items', 'prep_minutes')
    op.drop_column('menu_items', 'recipe')
    op.drop_column('menu_items', 'ingredients')
    op.drop_column('menu_items', 'romantic_price')
    op.drop_column('menu_items', 'drink_pairing')
    op.drop_column('menu_items', 'menu_description')
    op.drop_index(op.f('ix_image_cache_cache_key'), table_name='image_cache')
    op.create_index(op.f('ix_image_cache_cache_key'), 'image_cache', ['cache_key'], unique=False)
    op.create_unique_constraint(op.f('image_cache_cache_key_key'), 'image_cache', ['cache_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('image_cache', 'model',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_generated_file_kind'), 'generated_files', ['menu_id', 'kind'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_customers_telegram_user_id'), table_name='customers')
    op.create_index(op.f('ix_customers_telegram_user_id'), 'customers', ['telegram_user_id'], unique=False)
    op.create_unique_constraint(op.f('customers_telegram_user_id_key'), 'customers', ['telegram_user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('customers_phone_key'), 'customers', ['phone'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'city',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('customers', 'country',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('customers', 'language',
               existing_type=sa.Enum('UK', 'RU', 'EN', name='language', native_enum=False, length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('customers', 'phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('customers', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###

